### PR TITLE
Code optimization

### PR DESCRIPTION
**Pull request by MCMainiac**
I noticed you could summarize the `getChartData()` method from the `AdvancedPie` and `MultilineChart`, so I added a small abstract class `ComplexChart`, which is extended by both classes mentioned.

Also some warnings are now suppressed in the IntelliJ IDEA IDE.

### CODE REVIEW

**Comment by BrainStone** [comment]
Which IDE throws these warnings?

**Comment by sgdc3** [comment]
@BrainStone read the commit comments xD

**Comment by BrainStone** [comment]
Completely missed them xD

**Comment by MCMainiac** [comment]
Apart from the warnings, does the `ComplexChart` class make sense? It should work afaik. If so, please approve this pr or comment why it isn't useful :D

**Comment by BtoBastian** [comment]
Hey,
thank you for the PR!
However, I'm not sure if I like the changes:
- Suppressing warnings would just work for IntelliJ, all other IDEs would still show the same warnings (or even different ones). I don't think it's a good idea for a public project to include any code/files/... which are specific to a single IDE.
- I agree that in general it's good practice to reduce redundant code. However in this case I prefer keeping them seperated, as AdvancedPie charts and MultiLineChart do not really have anything in common (besides beging charts) and should therefore not inherit from the same class but "Chart". "ComplexChart" is far to abstract for me. It may also confuse less experienced developers, who may try to create an object of this new abstract class.
- You only added the "ComplexChart" to the Bukkit metrics class.

Thank you nevertheless, I appreciate every PR!

**Pull request closed without merging**
