### PR TITLE
Added debug option to all classes

### PR DESCRIPTION
**Pull request by BrainStone**

### CODE REVIEW

**Comment by sgdc3** [comment]
Please explain the point of that

**Comment by BrainStone** [comment]
If the option is enabled bStats will print the JSON data it is going to send to the console. This makes debugging a lot easier.

**Comment by sgdc3** [comment]
does it mmake sense to keep logFailedRequests separate?

**Comment by BrainStone** [comment]
I think so. Doesn't hurt to have these separate.

**Comment by MCMainiac** [comment]
This is.something I actually need right now for debugging!

**Comment by BrainStone** [comment]
In hindsight a different name for `debug` might make sense. Like `dumpJSON`, `debugJSON` or `printJSON`.

**Comment by BtoBastian** [comment]
Hey, thank you!
Is there any reason why you use [Logger#info(String)](https://www.slf4j.org/api/org/slf4j/Logger.html#info(java.lang.String)) instead of [Logger#debug(String)](https://www.slf4j.org/api/org/slf4j/Logger.html#debug(java.lang.String)) for the debug messages in Sponge? I'm not that familiar with Sponge, but afaik it does not just ignore lower level log messages like Bukkit does...
As a config name, maybe I would use something like `logSentData` or similar.

**Comment by BtoBastian** [comment]
Have you already tested the changes, if everything works as intended?

**Comment by BrainStone** [comment]
@BtoBastian Yes there is a reason. Debug messages don't show in the console at all. They get logged in the log file but that's it. And the point of the option is to print it in the console.

**Comment by BtoBastian** [comment]
Ohh, ok.

**Comment by BrainStone** [comment]
@BtoBastian so are you going to change it back, or should I?

**Comment by BtoBastian** [comment]
What's wrong with the data only being logged in a file?
What are the advantages of printing it into the console?

**Comment by BrainStone** [comment]
When I want to debug something I want to see it in the console.

**Comment by BtoBastian** [comment]
https://github.com/BtoBastian/bStats-Metrics/commit/2db0d7dc9654eb7c7442fe2b665461e5a1811d85 implements this, with the additional option to log the response from bStats.

**Pull request closed without merging**
